"""add users daily request quota columns

Revision ID: 4e14c7bab841
Revises: 98900a8d691c
Create Date: 2026-08-31 10:38:45.516241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e14c7bab841'
down_revision: Union[str, Sequence[str], None] = '98900a8d691c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default hand-added: models.py's default=0 is Python-side ORM
    # only, not DDL -- a NOT NULL column added with no server_default would
    # fail against a users table that already has rows (same class of
    # incident already documented in CLAUDE.md for the tour_guide_mode
    # migration; caught here by reading the generated file before applying
    # it, per that same incident's lesson).
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_request_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('daily_request_count_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_request_count_date')
    op.drop_column('users', 'daily_request_count')
    # ### end Alembic commands ###
