"""add conversations.tour_guide_mode

Revision ID: 65524d890048
Revises: f0fa120ecdf7
Create Date: 2026-08-27 17:51:52.012893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65524d890048'
down_revision: Union[str, Sequence[str], None] = 'f0fa120ecdf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default hand-added: models.py's default=False is Python-side
    # ORM only, not DDL -- a NOT NULL column added with no server_default
    # would fail against a conversations table that already has rows (see
    # CLAUDE.md's documented alembic/env.py incident for why generated
    # migrations always get read, not blindly applied).
    op.add_column(
        'conversations',
        sa.Column('tour_guide_mode', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'tour_guide_mode')
    # ### end Alembic commands ###
