"""add indexes on foreign key columns

Revision ID: 98900a8d691c
Revises: 65524d890048
Create Date: 2026-08-31 10:31:24.086709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98900a8d691c'
down_revision: Union[str, Sequence[str], None] = '65524d890048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres never auto-indexes a foreign key column the way it does a
    # primary key -- every one of these was previously a full-table-scan on
    # every query that filters by it (every ownership check, every
    # conversation/trip lookup). See CLAUDE.md's architecture review,
    # 2026-08-31.
    #
    # Plain (non-CONCURRENTLY) CREATE INDEX -- runs inside this migration's
    # transaction and briefly locks each table during the build, which is
    # fine at today's real row counts (low hundreds per table) but would be
    # the wrong call against a genuinely large, actively-written table
    # later: CREATE INDEX CONCURRENTLY avoids the lock but cannot run
    # inside a transaction, so a future large-table index migration should
    # NOT copy this one verbatim -- see Alembic's docs on
    # `postgresql_concurrently=True` + `with op.get_context().autocommit_block():`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_itinerary_items_trip_id'), 'itinerary_items', ['trip_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_trips_conversation_id'), 'trips', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_conversation_id'), table_name='trips')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_itinerary_items_trip_id'), table_name='itinerary_items')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    # ### end Alembic commands ###
